"""Initial migration

Revision ID: 04b1db3c6005
Revises: 
Create Date: 2026-01-04 05:27:39.280152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b1db3c6005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('stack', sa.String(length=200), nullable=True),
    sa.Column('goal', sa.String(length=300), nullable=True),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('demo_url', sa.String(length=200), nullable=True),
    sa.Column('image_public_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('project')
    # ### end Alembic commands ###
